spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: create-drop
    open-in-view: false