spring:
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  liquibase:
    parameters:
      ADMIN_HASHED_PASSWORD: ${ADMIN_HASHED_PASSWORD}
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: none
    open-in-view: false
logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: OFF
server:
  tomcat:
    max-http-form-post-size: 2MB
telegram:
  bot:
    token: ${BOT_TOKEN}
