spring:
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: validate
    open-in-view: false
telegram:
  bot:
    #username: ${BOT_USERNAME}
    token: ${BOT_TOKEN}
